# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Dependencies list in Cargo.{toml,lock}.
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
  # Dependencies listed in .github/workflows/*.yml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
